### ISSUE TITLE
Adding the miro and mood board to the README

### ISSUE THREAD

**Issue by malangadan** [ufosc/VisualNovel#14]
The miro will be used to organize the game flow and the mood board will give members a sense of each characters personality. Hyperlink these two urls in the README under resources.

Game loop flowchart: https://miro.com/welcomeonboard/QnRybW9VRlpCQU5nT3R4UGIxejlrRG12ZzdDalFlM01RN2R6MHFlclg0RmRaUzI0UmhZdXBMREZCUGRVU215eXwzNDU4NzY0NTE3ODI5MjgwMjEwfDI=?share_link_id=384176755076. 

Character mood board: https://miro.com/welcomeonboard/QnRybW9VRlpCQU5nT3R4UGIxejlrRG12ZzdDalFlM01RN2R6MHFlclg0RmRaUzI0UmhZdXBMREZCUGRVU215eXwzNDU4NzY0NTE3ODI5MjgwMjEwfDI=?share_link_id=384176755076

**Comment by Phantom0110** [comment]
I'm down to try this

**Comment by malangadan** [comment]
Go for it
