### ISSUE TITLE
Create a way for the player to input their name

### ISSUE THREAD

**Issue by malangadan** [ufosc/VisualNovel#2]
We want the player to choose their name at the beginning and store their name in a variable called `player_name`. Go into the scripts.rpy file and change the `label start` section to prompt the user to enter the name they want to use in the game. Test if the code works by adding this line of code `"Your name is [player_name]."` after you store the players desired name in `player_name`.

**Comment by Shivansh175** [comment]
hey there !
I am interested in solving this issue....but can u guide me how can i run your video game onto my pc?

**Comment by josephcabezas** [comment]
I got this 👍

**Comment by malangadan** [comment]
Joey you are an incredible human being that I respect.
