### ISSUE TITLE
Organize RenPy script

### ISSUE THREAD

**Issue by WilsonGoins** [ufosc/VisualNovel#29]
The script in the RenPy code is long and will only get longer. It needs to be organized such that it is readable, encapsulated, and more manageable.

**Comment by JMalegni** [comment]
I'll take this if that's cool. Also C++ is best girl

**Comment by WilsonG42** [comment]
> I'll take this if that's cool. Also C++ is best girl

Sounds good, python is my favorite though. Aka for help if you need

**Comment by ammaarym** [comment]
Hey, can I help out with this also?

**Comment by WilsonGoins** [comment]
Yes, @ammaarym. You can work on it with @JMalegni. The general premise is to review Ren'Py script structure from larger projects and set up directories and files to prepare us for this. Also update documentation accordingly. 

I would recommend looking for reference code in YouTube tutorials or projects on GitHub.

**Comment by renderby** [comment]
Hey @JMalegni, if you could submit a pull request with your commits to @WilsonGoins, I'd love to assist with this issue as well!

**Comment by JMalegni** [comment]
sure, I'll get it done tomorrow during CC

**Comment by ammaarym** [comment]
Hey! I have a few questions to start. How can I contact you @WilsonGoins ?

**Comment by WilsonG42** [comment]
email me @wilson.goins@ufl.edu
