### ISSUE TITLE
Implement and Troubleshoot User Name Input Feature in New Script

### ISSUE THREAD

**Issue by AntonCSalvador** [ufosc/VisualNovel#31]
We are currently facing an issue with the user name input feature in our new script. The game should allow players to enter their name, which will then be used throughout the game in dialogue and interactions. However, the current implementation in the new script is not functioning as expected.

We need someone to update the current game's code for the new script and make sure the entered name is stored correctly. 

Expected Behavior:
- When prompted, the player should be able to input their name.
- The game should then store this name and use it to personalize dialogues and interactions throughout the game.

**Comment by Xa-el** [comment]
I can add this feature!

**Comment by nickv779** [comment]
Changing the issue to this:
- Fix the current resolution and add an introduction explaining the context of the project to anyone who comes across the game
If you need any help, lmk @Xa-el

**Comment by Xa-el** [comment]
UPDATE: Found solution to resolution issue. The Renpy project resolution size was set to 1920 x 1080 when it was created meaning that all the backgrounds must also be 1920 x 1080 or the game will not be displayed properly. I will now be working on adding the introduction explaining the context of the project.
