### ISSUE TITLE
Rename Bytes of Love game file

### ISSUE THREAD

**Issue by WilsonGoins** [ufosc/VisualNovel#32]
Currently when you launch the Ren'Py application and want to select the project you want to launch the game is called "UFOSC". It should be renamed to "Bytes of Love". This will likely need you to refer to Ren'Py documentation.

**Comment by WilsonGoins** [comment]
We are not doing this until we get a good first release of the game because this will change the highest directory and could mess stuff up

**Comment by JMalegni** [comment]
can't believe we actually did it
