### ISSUE TITLE
Update README for MacOS users to contribute

### ISSUE THREAD

**Issue by nickv779** [ufosc/VisualNovel#34]
Make slight edit to the README so that clarification can be made for MacOS instructions as there is currently possible confusion when starting contribution.

**Comment by Myrtte** [comment]
Got it!

**Comment by nickv779** [comment]
Changing this issue into a reorganization of the README so information flows better. List the Maintainers first as that should be the immediate info that people read. Follow that with the installation section, though combine the Setup and Usage sections as the information in Usage is still you setting up the development environment.
