### ISSUE TITLE
Transfer 'Night Before Orientation' from Script Documentation into Ren'Py File

### ISSUE THREAD

**Issue by WilsonGoins** [ufosc/VisualNovel#40]
Transfer the script from the 'Night Before Orientation' section of the script document into Ren'Py code. Do this in a new .rpy file called 'Night_Before_Orientation.rpy'. Do not worry about adding in images, backgrounds, or sounds. Simply add the code and make sure that it functions when you through every different dialogue option. The different if blocks should be included as functions, NOT long lines of code inside the nested if statements.

Reach out to me if you need any help.

**Comment by ammaarym** [comment]
Hey, can I help out with this?
