### ISSUE TITLE
Include development builds

### ISSUE THREAD

**Issue by h1divp** [ufosc/VisualNovel#73]
It would be pretty cool, if periodically, there were compiled binaries for the game. So that way someone can just download and run it, without having to worry about setup.

Though this probably isn't that important right now.

**Comment by AntonCSalvador** [comment]
just figured out how to do this. uhh but its 127 mb.

**Comment by h1divp** [comment]
is that too much for github?? hmm

**Comment by AntonCSalvador** [comment]
more so for people cloning the repo, dont want to take up too much storage

**Comment by AntonCSalvador** [comment]
maybe we could put a sep download for it

**Comment by AntonCSalvador** [comment]
in the readme

**Comment by h1divp** [comment]
A link in the readme would probably be much better then, I did not think about the cloning LOL

**Comment by AntonCSalvador** [comment]
Just solved for the next pr

**Comment by JMalegni** [comment]
awesome suggestion, and good job executing it.
