### ISSUE TITLE
Create Bytes of Love website

### ISSUE THREAD

**Issue by AntonCSalvador** [ufosc/VisualNovel#80]
Like a website for the game because the homepage shouldnt be the github
Examples: 
- https://ddlc.moe/
- https://steins-gate.us/

**Comment by jonana-split** [comment]
Hi! I'd love to help with the website

**Comment by AntonCSalvador** [comment]
Hi @jonana-split ! We actually currently have a repo for the BytesOfLove website and you can def contribute there. https://github.com/ufosc/BytesOfLoveWebsite
