### ISSUE TITLE
Fix name setting

### ISSUE THREAD

**Issue by WilsonGoins** [ufosc/VisualNovel#81]
When the player is prompted to pick a name for themselves at the start of the game, we have two issues. First, we want the name to only be one word. We are correctly identifying when the name is more than one word, but the error message is "Please only enter alphabets", which isn't very clear. Please fix the error message to be more clear.

Also, let's make sure that after we get the name from the user we automatically capitalize the first letter, so "mark" would become "Mark".

**Comment by Teja-11** [comment]
can i work on this?

**Comment by WilsonGoins** [comment]
> can i work on this?

Yes, if you have any questions hit us up in the discord or on here.

**Comment by tejachalla123** [comment]
Hi @WilsonGoins, 

Fixed the error message and capitalize the first letter.

<img width="961" alt="Screenshot 2024-04-15 at 6 40 37 PM" src="https://github.com/ufosc/VisualNovel/assets/160343777/3e790df3-22e4-4ab1-830a-f52b762bf954">

<img width="963" alt="Screenshot 2024-04-15 at 6 40 51 PM" src="https://github.com/ufosc/VisualNovel/assets/160343777/236cd80a-5d9b-4077-b515-28ee85e72204">

<img width="894" alt="Screenshot 2024-04-15 at 6 41 09 PM" src="https://github.com/ufosc/VisualNovel/assets/160343777/713bdc05-c466-43f1-ba38-ab08da2850d8">

<img width="886" alt="Screenshot 2024-04-15 at 6 41 19 PM" src="https://github.com/ufosc/VisualNovel/assets/160343777/739d5b11-f62a-420a-9ec5-cb7063638856">

**Comment by Teja-11** [comment]
Hi @WilsonGoins,

Fixed error message and capitalize the first letter

<img width="876" alt="Screenshot 2024-04-15 at 6 48 08 PM" src="https://github.com/ufosc/VisualNovel/assets/60323760/0736b174-80f0-4455-9b94-747043993c52">


<img width="827" alt="Screenshot 2024-04-15 at 6 48 23 PM" src="https://github.com/ufosc/VisualNovel/assets/60323760/d3766177-d4c9-486c-914d-bf7754972317">


<img width="794" alt="Screenshot 2024-04-15 at 6 48 46 PM" src="https://github.com/ufosc/VisualNovel/assets/60323760/cad30e22-f77b-4050-9f8d-ce521793ddb1">


<img width="528" alt="Screenshot 2024-04-15 at 6 48 58 PM" src="https://github.com/ufosc/VisualNovel/assets/60323760/3fb2d4e6-d505-4743-b398-c85a3bdaff2e">

**Comment by WilsonGoins** [comment]
Awesome, make a pull request and we will get it in the game soon! Come by casual coding Tuesdays and Thursdays 5-7 in Turlington L011 if you want to work on it more!
