### ISSUE TITLE
Fix control buttons at bottom of screen during gameplay

### ISSUE THREAD

**Issue by JMalegni** [ufosc/VisualNovel#84]
![image](https://github.com/ufosc/VisualNovel/assets/108361625/785c17a3-42a4-44ec-8ae8-410de979be04)
There are a series of light grey buttons at the bottom of the screen that are very difficult to read due to the change of the dialogue box, maybe changing the color and location of the buttons would solve the issue.

**Comment by Shayan414** [comment]
Hi there, can I be assigned this issue?

**Comment by JMalegni** [comment]
of course

**Comment by ryanjalloul** [comment]
Can I be assigned the issue as well? I just got checked off for an assignment that for a grade and i said i could work on this

**Comment by JMalegni** [comment]
Sure, I imagine this is for introduction to SWE. After you finish, feel free to actually make the pr. Not too sure what happened to Shayan.

**Comment by jingyifu1225** [comment]
Hi! I could help with this issue!

**Comment by SamsonCart** [comment]
Hello! May I be assigned this issue please?

**Comment by qwasmos** [comment]
Hello, May I also be assigned to this issue? I should have asked this much earlier as well.

**Comment by SamsonCart** [comment]
I submitted a pull request for this issue. I would love to consult with a design lead about making a more appropriate choice for the palette. The legibility has now improved, and the selected color scheme was built off the mood board, but I think there's room for improvement.

**Comment by JMalegni** [comment]
> I submitted a pull request for this issue. I would love to consult with a design lead about making a more appropriate choice for the palette. The legibility has now improved, and the selected color scheme was built off the mood board, but I think there's room for improvement.

Awesome, I am still waiting to accept prs for this issue as a few others are using it for their assignments. But feel free to hop in the discord and chat in any of the Bytes of Love channels. Since it is summer, our artists may not be active, but we are always happy to talk about the game.

**Comment by JMalegni** [comment]
Thank you all for your work, I hope everyone got a 100 for the assignment
