### ISSUE TITLE
Add Black Border to Text in Options and Character Names

### ISSUE THREAD

**Issue by AntonCSalvador** [ufosc/VisualNovel#93]
### Description
To improve readability and visual clarity, we need to add a small black border around the text in the options menu and the names of characters within the game.

### Objective
- Implement a subtle black border around all text elements in the options menu.
- Apply the same border to character names displayed during dialogues.
- Ensure that the border enhances readability without overpowering the existing design.

### Implementation Details
- The border should be thin enough to be noticeable but not too thick to distract from the overall aesthetics.
- Consistent border styling should be applied across all relevant text elements.

### Screenshot
![oooo](https://github.com/user-attachments/assets/aa07d026-9eaa-439f-835a-663166d51673)

### Testing
- Verify that the text remains legible and aesthetically pleasing with the border applied.
- Test the changes across different screen resolutions to ensure consistent appearance.

### Additional Context
- The goal is to maintain the existing design's style while improving text visibility. Any changes should be subtle and in line with the game's visual theme.

---

**Severity:** Low  
**Priority:** Medium

**Comment by sahilpatel342** [comment]
Hello, is this still open, if so could I work on it?

**Comment by AntonCSalvador** [comment]
@sahilpatel342 Hey! I got you. Thanks for picking this issue up!
