### ISSUE TITLE
Replace Character Sprites with Updated Versions

### ISSUE THREAD

**Issue by WilsonGoins** [ufosc/VisualNovel#98]
### Description
Some of the current character sprites in BytesOfLove have a very discrete water mark somewhere on the upperhalf of the torso. We need to replace the relevant character sprites with the un-watermarked versions. 

### Objective
- Replace faulty character sprites with unwatermarked ones.

### Resources
- Claim this issue and then send a message in our Discord to let us know that you are working on this. We will then grant you access to the new character sprites and to a list of all the characters sprites which are watermarked (so you what to replace and with what to replace it).
- Attached is a screenshot of a sprite that is watermarked (it is just underneath her left hand).

### Collaboration
- We encourage collaboration on this redesign effort.
- Feel free to discuss ideas and share progress through our [Discord](https://discord.gg/gyRvuAXB) and this chat.

### Expected Deliverables
- Characters without watermarks throughout the entire game.

### Screenshot
![Screenshot 2024-09-02 130933](https://github.com/user-attachments/assets/d939c318-9393-4e95-91b3-3936ab05dfbc)

### Additional Context
- This is a great opportunity for contributors to showcase their design skills and contribute to an exciting project.

---

**Severity:** Medium
**Priority:** High

**Comment by EdleyF** [comment]
Is this still up for grabs?
If so I'd like to tackle it please

**Comment by WilsonGoins** [comment]
> Is this still up for grabs? If so I'd like to tackle it please

All yours, pop into the Discord if you have any questions.
